"""Flask extensions, created once and bound to each app in ``init_extensions``."""

from datetime import datetime
from pathlib import Path

from flask import Flask, current_app, has_request_context
from flask_jwt_extended import JWTManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from redis import Redis
from sqlalchemy import Connection, DateTime, Engine, MetaData, create_engine, event, text
from sqlalchemy.orm import DeclarativeBase, Session, SessionTransaction, registry

from app.ai.registry import ModelRegistry
from app.config import Settings, current_settings

# Deterministic constraint and index names, so autogenerated migrations are
# stable and a constraint can be dropped by name in a later migration.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# Absolute, so migrations are found whatever the working directory is.
MIGRATIONS_DIR = Path(__file__).resolve().parents[1] / "migrations"

# The refresh cookie is only sent to the endpoints that consume it.
REFRESH_COOKIE_PATH = "/api/auth"

_REDIS_EXTENSION_KEY = "datapilot.redis"
_READONLY_ENGINE_EXTENSION_KEY = "datapilot.readonly_engine"
_MODEL_REGISTRY_EXTENSION_KEY = "datapilot.model_registry"
# Ask your data runs one query per request, so a few connections per process
# are plenty; the cap also bounds what the read-only role can hold open.
_READONLY_POOL_SIZE = 2
_READONLY_MAX_OVERFLOW = 3
# Fail fast when Redis is unreachable instead of holding a worker for the
# library's default of no timeout at all.
_REDIS_TIMEOUT_SECONDS = 2.0
_DATABASE_CONNECT_TIMEOUT_SECONDS = 5


class Base(DeclarativeBase):
    """Declarative base of every model.

    Models subclass this rather than ``db.Model``: they share its metadata, so
    Flask-SQLAlchemy and Alembic see them all the same, and mypy can type
    them, which it cannot do for the dynamically built ``db.Model``.
    """

    # Set through the registry rather than as class attributes, because
    # Flask-SQLAlchemy subclasses this base to build db.Model.
    registry = registry(
        metadata=MetaData(naming_convention=NAMING_CONVENTION),
        # Every timestamp is an instant (timestamptz); a naive datetime cannot
        # be compared or serialized as UTC without guessing its zone.
        type_annotation_map={datetime: DateTime(timezone=True)},
    )


db = SQLAlchemy(model_class=Base)
migrate = Migrate()
jwt = JWTManager()


# On the Session class, so every session a request uses is covered, whoever built it.
@event.listens_for(Session, "after_begin")
def _limit_request_statements(
    _session: Session, _transaction: SessionTransaction, connection: Connection
) -> None:
    """Cap every statement a request runs; errors.py turns a cancelled one into a 503.

    Requests only: CLI commands (seeding, migrations) legitimately run long
    statements on the same engine. ``is_local`` scopes the value to this
    transaction, so it never leaks into the next user of a pooled connection.
    """
    if has_request_context():
        timeout = f"{current_settings().api_statement_timeout_ms}ms"
        connection.execute(
            text("SELECT set_config('statement_timeout', :timeout, true)"), {"timeout": timeout}
        )


def init_extensions(app: Flask, settings: Settings) -> None:
    """Configure and bind every extension to ``app``."""
    app.config.update(
        SQLALCHEMY_DATABASE_URI=str(settings.database_url),
        SQLALCHEMY_ENGINE_OPTIONS={
            # Replaces connections the server closed while they sat in the pool.
            "pool_pre_ping": True,
            "connect_args": {"connect_timeout": _DATABASE_CONNECT_TIMEOUT_SECONDS},
        },
        JWT_SECRET_KEY=settings.jwt_secret_key.get_secret_value(),
        # Access tokens travel in the Authorization header, refresh tokens in
        # a cookie; each endpoint names the one location it accepts.
        JWT_TOKEN_LOCATION=["headers", "cookies"],
        JWT_ACCESS_TOKEN_EXPIRES=settings.access_token_ttl,
        JWT_REFRESH_TOKEN_EXPIRES=settings.refresh_token_ttl,
        JWT_REFRESH_COOKIE_PATH=REFRESH_COOKIE_PATH,
        # The CSRF cookie must be readable by the single-page app, which runs
        # at "/": document.cookie only lists cookies whose path covers the page.
        JWT_REFRESH_CSRF_COOKIE_PATH="/",
        JWT_COOKIE_SAMESITE="Strict",
        JWT_COOKIE_SECURE=settings.is_production,
        JWT_COOKIE_CSRF_PROTECT=True,
        # Persistent cookies, so staying logged in survives a browser restart.
        # start_session sets their Max-Age to the refresh token lifetime.
        JWT_SESSION_COOKIE=False,
    )
    db.init_app(app)
    migrate.init_app(app, db, directory=str(MIGRATIONS_DIR), compare_type=True)
    jwt.init_app(app)
    # A separate engine, not a bind of Flask-SQLAlchemy: nothing in the
    # application may run on it by accident through the shared session.
    app.extensions[_READONLY_ENGINE_EXTENSION_KEY] = create_engine(
        str(settings.readonly_database_url),
        pool_size=_READONLY_POOL_SIZE,
        max_overflow=_READONLY_MAX_OVERFLOW,
        pool_pre_ping=True,
        connect_args={"connect_timeout": _DATABASE_CONNECT_TIMEOUT_SECONDS},
    )
    # Built here so a registry that contradicts the settings stops the app
    # at startup, not on the first question.
    app.extensions[_MODEL_REGISTRY_EXTENSION_KEY] = ModelRegistry.from_settings(
        models_file=settings.llm_models_file,
        api_keys=settings.llm_api_keys,
        default_model=settings.llm_default_model,
        fallback_models=settings.llm_fallback_models,
    )
    app.extensions[_REDIS_EXTENSION_KEY] = Redis.from_url(
        str(settings.redis_url),
        decode_responses=True,
        socket_connect_timeout=_REDIS_TIMEOUT_SECONDS,
        socket_timeout=_REDIS_TIMEOUT_SECONDS,
    )


def get_redis() -> Redis:
    """Return the Redis client of the current application."""
    client: Redis = current_app.extensions[_REDIS_EXTENSION_KEY]
    return client


def get_readonly_engine() -> Engine:
    """Return the engine that connects as the read-only role, for model-written SQL only."""
    engine: Engine = current_app.extensions[_READONLY_ENGINE_EXTENSION_KEY]
    return engine


def get_model_registry() -> ModelRegistry:
    """Return the models Ask your data may use in the current application."""
    registry: ModelRegistry = current_app.extensions[_MODEL_REGISTRY_EXTENSION_KEY]
    return registry
