"""Fixed reference lists the generator draws from.

Weights are relative, not percentages that must add up to 100; they read as
"out of 100" here only because that is easiest to review.
"""

from dataclasses import dataclass

# ISO 3166-1 alpha-2 codes and their share of customers. A few markets
# dominate, as in most stores: the top three hold close to half.
COUNTRY_WEIGHTS: dict[str, float] = {
    "US": 26,
    "GB": 11,
    "DE": 10,
    "FR": 7,
    "CA": 6,
    "AU": 5,
    "NL": 4,
    "ES": 4,
    "IT": 4,
    "SE": 3,
    "PL": 3,
    "BR": 3,
    "JP": 2.5,
    "IN": 2.5,
    "MX": 2,
    "IE": 1.5,
    "BE": 1.5,
    "CH": 1.5,
    "AT": 1.5,
    "DK": 1,
}


@dataclass(frozen=True, slots=True)
class Category:
    name: str
    catalog_share: float
    # Prices are log-normal: most products sit near the median, a few cost
    # several times more. A spread of 0.6 puts about two thirds of prices
    # between median / 1.8 and median x 1.8.
    median_price: float
    price_spread: float
    nouns: tuple[str, ...]


CATEGORIES: tuple[Category, ...] = (
    Category(
        "Electronics",
        15,
        89,
        0.8,
        (
            "Headphones",
            "Speaker",
            "Charger",
            "Keyboard",
            "Mouse",
            "Webcam",
            "Monitor",
            "Power Bank",
            "Smartwatch",
            "Router",
            "USB Hub",
            "Earbuds",
        ),
    ),
    Category(
        "Home & Kitchen",
        15,
        35,
        0.7,
        (
            "Desk Lamp",
            "Kettle",
            "Blender",
            "Cookware Set",
            "Knife Set",
            "Cutting Board",
            "Coffee Grinder",
            "Toaster",
            "Throw Blanket",
            "Storage Box",
        ),
    ),
    Category(
        "Clothing",
        14,
        39,
        0.6,
        (
            "T-Shirt",
            "Hoodie",
            "Jeans",
            "Jacket",
            "Sneakers",
            "Scarf",
            "Beanie",
            "Rain Coat",
            "Socks Pack",
            "Polo Shirt",
        ),
    ),
    Category(
        "Books",
        10,
        18,
        0.4,
        (
            "Field Guide",
            "Cookbook",
            "Novel",
            "Atlas",
            "Workbook",
            "Biography",
            "Poetry Collection",
            "Comic Volume",
            "Language Course",
            "Photo Book",
        ),
    ),
    Category(
        "Sports & Outdoors",
        10,
        45,
        0.8,
        (
            "Yoga Mat",
            "Water Bottle",
            "Tent",
            "Backpack",
            "Running Shorts",
            "Dumbbell Set",
            "Bike Light",
            "Hiking Poles",
            "Jump Rope",
            "Sleeping Bag",
        ),
    ),
    Category(
        "Beauty",
        9,
        22,
        0.6,
        (
            "Face Serum",
            "Shampoo",
            "Lip Balm",
            "Hand Cream",
            "Perfume",
            "Sunscreen",
            "Hair Dryer",
            "Nail Kit",
            "Body Wash",
            "Face Mask",
        ),
    ),
    Category(
        "Toys & Games",
        8,
        29,
        0.7,
        (
            "Board Game",
            "Puzzle",
            "Building Set",
            "Plush Bear",
            "RC Car",
            "Card Game",
            "Kite",
            "Doll House",
            "Science Kit",
            "Train Set",
        ),
    ),
    Category(
        "Office",
        7,
        24,
        0.8,
        (
            "Desk Organizer",
            "Notebook Set",
            "Pen Set",
            "Seat Cushion",
            "Monitor Stand",
            "Paper Shredder",
            "Label Maker",
            "Planner",
            "Whiteboard",
            "Desk Mat",
        ),
    ),
    Category(
        "Garden",
        6,
        34,
        0.8,
        (
            "Planter",
            "Hose",
            "Pruning Shears",
            "Bird Feeder",
            "Seed Kit",
            "Garden Gloves",
            "Sprinkler",
            "Watering Can",
            "Solar Lantern",
            "Compost Bin",
        ),
    ),
    Category(
        "Grocery",
        6,
        12,
        0.5,
        (
            "Coffee Beans",
            "Green Tea",
            "Olive Oil",
            "Dark Chocolate",
            "Granola",
            "Honey",
            "Pasta Set",
            "Spice Kit",
            "Hot Sauce",
            "Protein Bars",
        ),
    ),
)

# Combined with a category noun: "Summit Backpack", "Nova Earbuds".
PRODUCT_LINES = (
    "Aurora",
    "Summit",
    "Nimbus",
    "Harbor",
    "Cedar",
    "Lumen",
    "Atlas",
    "Vista",
    "Nova",
    "Pioneer",
    "Ember",
    "Coastal",
    "Alpine",
    "Urban",
    "Willow",
    "Granite",
    "Meadow",
    "Orbit",
    "Polar",
    "Sierra",
    "Tidal",
    "Echo",
    "Maple",
    "Zephyr",
)

FIRST_NAMES = (
    "Ada",
    "Alex",
    "Amara",
    "Ana",
    "Ben",
    "Carla",
    "Chen",
    "Daniel",
    "Elena",
    "Emma",
    "Felix",
    "Grace",
    "Hana",
    "Ivan",
    "Jonas",
    "Julia",
    "Kai",
    "Laura",
    "Leo",
    "Lucas",
    "Maya",
    "Mia",
    "Noah",
    "Nora",
    "Omar",
    "Priya",
    "Rafael",
    "Rosa",
    "Sam",
    "Sofia",
    "Tom",
    "Yuki",
)

LAST_NAMES = (
    "Andersen",
    "Bauer",
    "Costa",
    "Dubois",
    "Evans",
    "Fischer",
    "Garcia",
    "Hughes",
    "Ito",
    "Jensen",
    "Kowalski",
    "Lima",
    "Martin",
    "Novak",
    "Okafor",
    "Patel",
    "Quinn",
    "Rossi",
    "Schmidt",
    "Silva",
    "Smith",
    "Tanaka",
    "Varga",
    "Weber",
    "Wright",
    "Young",
)
